---
name: Alien-Libjio
version: 1.003
author:
  - 'Jonathan Yu <jawnsy@cpan.org>'
abstract: Utility package to install and locate libjio
license: unrestricted
requires:
  perl: 5.006
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0.62
  Test::NoWarnings: 0.084
dynamic_config: 1
provides:
  Alien::Libjio:
    file: lib/Alien/Libjio.pm
    version: 1.003
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
resources:
  Ratings: http://cpanratings.perl.org/d/Alien-Libjio
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Alien-Libjio
  license: http://edwardsamuels.com/copyright/beyond/articles/public.html
  repository: http://svn.ali.as/cpan/trunk/Alien-Libjio
